a:
	lex parser.l && gcc lex.yy.c -o parser && ./parser < l2z1a.txt > solution_a && diff solution_a l2z1a.r1.txt	

b:
	lex parser.l && gcc lex.yy.c -o parser && ./parser < l2z1b.txt > solution_b && diff solution_b l2z1b.r1.txt	
